version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
      # Build and install basana.
      - poetry build
      - pip install dist/basana-`poetry version -s`.tar.gz[charts]

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
